# Generated by Django 3.0.2 on 2020-02-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('genre', models.TextField(max_length=50)),
                ('price', models.FloatField()),
                ('author', models.TextField(default=None, max_length=50)),
                ('description', models.TextField(default=None, max_length=500)),
                ('cover', models.URLField(default=None, max_length=500)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
